package Server;

import com.sun.net.httpserver.HttpExchange;
import com.sun.net.httpserver.HttpsConfigurator;
import com.sun.net.httpserver.HttpsParameters;
import com.sun.net.httpserver.HttpsServer;

import javax.net.ssl.KeyManagerFactory;
import javax.net.ssl.SSLContext;
import javax.net.ssl.SSLEngine;
import javax.net.ssl.SSLParameters;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.OutputStream;
import java.net.InetSocketAddress;
import java.security.KeyStore;

public class PostGetServer {
    // activity servicing is created on start

    public static void serverStarter() throws Exception {
        // Security setup section
        // Passphrase is generated by accessing the generated keystore.jks file
        char[] passphrase = "password".toCharArray();
        KeyStore ks = KeyStore.getInstance("JKS");
        try (FileInputStream fis = new FileInputStream( "keystore.jks")) {
            ks.load(fis, passphrase);
        }

        // maybe use following instead of try block?
        // ks.load(new FileInputStream("keystore.jks"), passphrase);

        // The specific algorithm and protocol is defined
        KeyManagerFactory kmf = KeyManagerFactory.getInstance("SunX509");
        kmf.init(ks, passphrase);

        SSLContext sslContext = SSLContext.getInstance("TLSv1.3"); // forced TLS 1.3
        sslContext.init(kmf.getKeyManagers(), null, null);

        // Creates HTTPS server on localport 8443
        HttpsServer server = HttpsServer.create(new InetSocketAddress(8443), 0);
        server.setHttpsConfigurator(new HttpsConfigurator(sslContext) {
            public void configure(HttpsParameters p) {
                SSLEngine e = sslContext.createSSLEngine();
                p.setProtocols(new String[]{"TLSv1.3"});
                p.setCipherSuites(e.getEnabledCipherSuites());
                SSLParameters sp = sslContext.getDefaultSSLParameters();
                sp.setProtocols(new String[]{"TLSv1.3"});
                p.setSSLParameters(sp);
            }
        });

        // we allow different methods and headers this will be seen by the users pc so it knows methods and such

        server.createContext("/server", PostGetServer::handleRequest);

        // activity service initialized on start before server
        server.start();
        System.out.println("HTTPS server running on https://localhost:8443/server");
    }

    private static void handleRequest(HttpExchange exchange) {
        // CORS headers
        exchange.getResponseHeaders().add("Access-Control-Allow-Origin", "*");
        exchange.getResponseHeaders().add("Access-Control-Allow-Methods", "GET, POST, OPTIONS");
        exchange.getResponseHeaders().add("Access-Control-Allow-Headers", "Content-Type");

        // Compacted The methodSwitch see getHandler and postHandler to add methods :D
        String method = exchange.getRequestMethod();
        if ("OPTIONS".equalsIgnoreCase(method)) {
            try {
                exchange.sendResponseHeaders(204, -1); // No content
            } catch (IOException e) {
                throw new RuntimeException(e);
            }
            exchange.close();
            return;
        }

        String response = null;
        try {
            response = methodSwitch(exchange);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }

        assert response != null;
        byte[] bytes = response.getBytes();
        try {
            exchange.sendResponseHeaders(200, bytes.length);
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
        try (OutputStream os = exchange.getResponseBody()) {
                os.write(bytes);
            } catch (IOException e) {
            throw new RuntimeException(e);
        }
    }

    private static String methodSwitch(HttpExchange exchange) throws Exception {
        //importing get and post functionality see the corresponding files for more info
        GetHandler getHandler = new GetHandler();
        PostHandler postHandler = new PostHandler();


        // We find out what method (get, post or options) the user has requested
        String method = exchange.getRequestMethod();
        String response;


        switch (method) {    // this switch redirects the exchange to the correct handler.
            case "OPTIONS":  // options returns response headers that we defined previously
                exchange.sendResponseHeaders(204, -1);
                exchange.close();  // Important or else it gets mad rahhhhh
                return null; 

            case "GET":
                response = getHandler.handle(exchange);
                System.out.println(response);
                break;

            case "POST":
                response = postHandler.handle(exchange);
                System.out.println(response);
                break;

            default:
                // catches error methods
                response = "Unsupported method: " + method;
        }

        return response;
    }
}