package Server;

import com.sun.net.httpserver.*;
import javax.net.ssl.*;
import java.io.*;
import java.net.*;
import java.security.*;


public class PostGetServer {
    public static void main(String[] args) throws Exception {


        // Security setup section
        //Passphrase is generated by accessing the generated keystore.jks file
        char[] passphrase = "password".toCharArray();
        KeyStore ks = KeyStore.getInstance("JKS");
        try (FileInputStream fis = new FileInputStream("keystore.jks")) {
            ks.load(fis, passphrase);
        }

        //The specific algorithm and protocol is defined.
        KeyManagerFactory kmf = KeyManagerFactory.getInstance("SunX509");
        kmf.init(ks, passphrase);
        SSLContext sslContext = SSLContext.getInstance("TLS");
        sslContext.init(kmf.getKeyManagers(), null, null);

        // Creates HTTPS server on localport 8443
        HttpsServer server = HttpsServer.create(new InetSocketAddress(8443), 0);
        server.setHttpsConfigurator(new HttpsConfigurator(sslContext));

        //we allow different methods and headers this will be seen by the users pc so it knows methods and such
        server.createContext("/server", exchange -> {
            exchange.getResponseHeaders().add("Access-Control-Allow-Origin", "*");
            exchange.getResponseHeaders().add("Access-Control-Allow-Methods", "GET, POST, OPTIONS");
            exchange.getResponseHeaders().add("Access-Control-Allow-Headers", "Content-Type");

            // Compacted The methodSwitch see getHandler and postHandler to add methods :D
            String response = methodSwitch(exchange);


            // Sends response back to client computer
            byte[] bytes = response.getBytes();
            exchange.sendResponseHeaders(200, bytes.length);
            try (OutputStream os = exchange.getResponseBody()) {
                os.write(bytes);
            }

        });

        server.start();
        System.out.println("HTTPS server running on https://localhost:8443/server");
    }



    private static String methodSwitch(HttpExchange exchange) throws IOException {
        //importing get and post functionality see the corresponding files for more info
        GetHandler getHandler = new GetHandler();
        PostHandler postHandler = new PostHandler();


        // We find out what method (get, post or options) the user has requested
        String method = exchange.getRequestMethod();
        String response;


        switch (method) {    // this switch redirects the exchange to the correct handler.
            case "OPTIONS":  // options returns response headers that we defined previously
                exchange.sendResponseHeaders(204, -1);
                return "";

            case "GET":
                response = getHandler.handle(exchange);
                break;

            case "POST":
                response = postHandler.handle(exchange);
                break;

            default:
                //catches error methods
                response = "Unsupported method: " + method;
        }

        return response;
    }
}